### ISSUE TITLE
Problems with positioning

### ISSUE THREAD

**Issue by kexhest** [bevacqua/bullseye#1]
Hi, I've been experimenting with rome which is really awesome! But I have problems with the positioning of the calendar. In my case I narrowed it down to a problem within this package. The "constructor" in bullseye.js overwrites "target" with "el" which means that when calling getBoundingClientRect on target it always reads top: 0 and left: 0 since it's a new absolutely positioned element appended to body. This means it never attaches itself to the real "target".

Is this meant to be working or is it me who is doing something wrong? If I just revert the first lines in bullseye.js to the state before the last commit everything works as expected.

Thanks.

**Comment by bevacqua** [comment]
Let me know if #2 fixes it, and I'll merge / update rome.

**Comment by kexhest** [comment]
That seems to have solved my issue. :+1:
